### ISSUE TITLE
Request for Pre-trained Model Checkpoints (r50_m.tar)

### ISSUE THREAD

**Issue by yctsai-hub** [Soombit-ai/cxr-clip#13]
Hello,

Thank you for your amazing work on CXR-CLIP! I am currently trying to use the pre-trained model as described in the documentation, specifically the ResNet50 model (r50_m.tar). However, I couldn’t find any links or instructions on how to download this checkpoint from the repository or documentation.

Could you please provide information on where I can access the pre-trained model checkpoints for CXR-CLIP? If possible, a direct download link or further instructions would be greatly appreciated.

Thank you in advance for your assistance!

**Comment by kihyunU** [comment]
here is the dowonload link. It is on README
https://twg.kakaocdn.net/brainrepo/models/cxr-clip/f982386ef38aa3ecd6ce1f8f928e8aa8/r50_m.tar
